<?php

/**
 * @file
 * This module adds user reputations to the Answers service
 * 
 * @author Chip Cleary
 * 
 */

 include_once('aup.features.inc');

 /**
 * Implement hook_help().
 */
function aup_help($path, $arg) {
  switch ($path) {
    case "admin/help#modulename":
      return '<p>'. t('Adds user reputations to the Answers service.') .'</p>';
  }
}

/*
 * Implement hook_preprocess
 * 
 * Add point total next to "submitted" information on question and answer nodes
 */

function aup_preprocess(&$vars, $hook) {
  // Only do this for question and answer nodes
  if (isset($vars['type'])) {
    if ($vars['type'] == 'question' || $vars['type'] == 'answer') {
      // Only do this for authorized users (not anonymous)
      if ($vars['uid']) {
        // Add a variable for use by custom templates as well as update the 'submitted' variable for use by standard themes
        $terms = taxonomy_get_term_by_name('Answers Reputation');
        $term = array_shift($terms);
        $answers_reputation = userpoints_get_current_points($vars['uid'], $term->tid);
        $vars['submitted'] .= ' (' . $answers_reputation . ')';
        $vars['answers_reputation'] = $answers_reputation;
      }
    }
 }
}
