<?php
/**
 * @file
 * Provide import/export functionality for mail_edit module.
 */

/**
 * Implementation of hook_features_api().
 */
function mail_edit_features_features_api() {
  return array(
    'mail_edit_features' => array(
      'name' => t('Mail edit templates'),
      'features_source' => TRUE,
      'default_hook' => 'default_mail_edit_features',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'file' => drupal_get_path('module', 'mail_edit_features') . '/inc/mail_edit_features.features.inc',
    ),
  );
}

/**
 * Function converts array to string.
 */
function mail_edit_features_string_get($identifier) {
  list($id, $language) = explode('--', $identifier);
  $convert = '';

  $res = db_query("SELECT me.*, mer.module, mer.mailkey, mer.description AS registry_description " .
    "FROM {mail_edit_registry} mer " .
    "JOIN {mail_edit} me ON mer.id = me.id " .
    "WHERE me.id = :id AND me.language = :lan", array(":id" => $id , ":lan" => $language))
    ->fetchAssoc();

  if (!empty($res)) {
    $convert = features_var_export($res, '  ') . ";";
  }
  return $convert;
}

/**
 * Get current settings for mail_edit.
 */
function mail_edit_features_content_get() {
  $query = db_query('SELECT me.id, me.language FROM {mail_edit_registry} mer' .
    ' JOIN {mail_edit} me ON mer.id = me.id');
  $templates = array();
  foreach ($query as $result) {
    $templates[$result->id . '--' . $result->language] = $result;
  }

  return $templates;
}
