<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function lesson_questions_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "quicktabs" && $api == "quicktabs") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function lesson_questions_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'lesson_questions') . '/views',);
}

/**
 * Implements hook_init().
 */
function lesson_questions_init() {
  drupal_add_js(drupal_get_path('module', 'lesson_questions') . '/lesson_questions.js');
  drupal_add_js(drupal_get_path('module', 'lesson_questions') . '/lesson_youtube_jsapi.js');
}

/**
 * Implements hook_block_info()
 */
function lesson_questions_block_info() {
  $block['lesson_questions'] = array(
    'info' => 'Lesson Questions',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $block['lesson_lecturer_notes'] = array(
    'info' => 'Lesson Notes',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $block;
}

/**
 * Implementation of hook_block_view()
 */
function lesson_questions_block_view($delta = '') {
  $content = array();

  switch($delta) {
    case 'lesson_questions':
      // Question form
      $content['question_form'] = drupal_get_form('quick_question');
      //Placeholder for message. 
      $content['message_placeholder'] = array(
        '#type' => 'markup',
        '#markup' => '<div id="message-placeholder"></div>',
      );
      // Embed view 
      $content['questions_list'] = array(
        '#type' => 'markup',
        '#markup' => _get_relevant_questions_list(),
      );
      // Build the block title and contents
      $block['subject'] = '';
      $block['content'] = $content;
      break;
    case 'lesson_lecturer_notes':
      //Lesson Node
      $lesson_node = menu_get_object('node');

      //Placeholder for message. 
      $content['message_placeholder'] = array(
        '#type' => 'markup',
        '#markup' => '<div id="message-placeholder"></div>',
      );
      // Notes form
      $content['lecturer_notes_form'] = drupal_get_form('lecturer_notes', $lesson_node);


      // Build the block title and contents
      $block['subject'] = '';
      $block['content'] = $content;
      break;
  }
  return $block;
}

/**
 * Callback function : Defines form for lecturer notes for lesson page.
 */
function lecturer_notes($form, &$form_state) {
  $lesson_node = $form_state['build_info']['args'][0]; 
  //check if its a lesson node and user has right to update(edit) it.
  if(!($lesson_node->type == 'lesson' || node_access('update', $lesson_node))) { 
    return NULL;
  }

  $form['#prefix'] = '<div id="lecturer-notes-wrapper">';
  $form['#suffix'] = '</div>';
  
  //Get default Values
  $items = field_get_items('node', $lesson_node, 'field_notes');
  $notes = field_view_value('node', $lesson_node, 'field_notes', $items[0]);
  
  $form['notes'] = array(
    '#type' => 'text_format',
    '#attributes' => array('placeholder' => t('Notes')),
    '#rows' => 3,
    '#cols' => 73,
    '#required' => TRUE,
    '#default_value' => render($notes),
    '#format' => NULL, //Default format
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#ajax' => array(
      'callback' => 'lecturer_notes_submit_callback',
      'wrapper' => 'lecturer-notes-wrapper',
    ),
    '#value' => t('Save'),
  );
  return $form;
}

/**
 * Callback function : Ajax callback function for quick_question form.
 */
function lecturer_notes_submit_callback($form, &$form_state) {
  $lesson_node = $form_state['build_info']['args'][0]; 
  
  //validations
  if (!$form_state['values']['notes']) {
    $message = t('Notes field is required');
    $commands[] = ajax_command_replace('#message-placeholder', _get_completion_text($message));
    return array('#type' => 'ajax', '#commands' => $commands);
  }

  $lesson_node->field_notes[$lesson_node->language][0]['value'] = $form_state['values']['notes']['value'];
  $lesson_node->field_notes[$lesson_node->language][0]['format'] = $form_state['values']['notes']['format'];
  node_save($lesson_node);

  $commands[] = ajax_command_replace('#message-placeholder', _get_completion_text(t('Notes Saved')));
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Callback function : Defines form for quick question for lesson page.
 */
function quick_question($form, &$form_state) {
  if (!user_access('create question content')) {
    return;
  }
  
  $form['quick_question'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#prefix' => '<div id="quick-question-wrapper">',
    '#suffix' => '</div>',
    '#title' => t('Ask Question')
  );
  $original_path = implode('/', arg());
  $compressed_path = relevant_answers_compress_string($original_path);
  $form['quick_question']['compressed_path'] = array(
    '#type' => 'hidden',
    '#value' => $compressed_path
  );

  $form['quick_question']['question'] = array(
    '#type' => 'textfield',
    '#attributes' => array('placeholder' => t('Question *')),
    '#required' => TRUE,
    '#size' => 75
  );

  $form['quick_question']['description'] = array(
    '#type' => 'textarea',
    '#attributes' => array('placeholder' => t('Description')),
    '#rows' => 3,
    '#cols' => 73,
  );

  $form['quick_question']['submit'] = array(
    '#type' => 'submit',
    '#ajax' => array(
      'callback' => 'quick_question_submit_callback',
      'wrapper' => 'quick-question-wrapper',
    ),
    '#value' => t('Ask'),
  );
  return $form;
}

/**
 * Callback function : Ajax callback function for quick_question form.
 */
function quick_question_submit_callback($form, &$form_state) {
  global $user;
  $original_path = relevant_answers_decompress_string($form_state['values']['compressed_path']);

  //validations
  if (!$form_state['values']['question']) {
    $message = t('Question field is required');
    $commands[] = ajax_command_replace('#message-placeholder', _get_completion_text($message));
    return array('#type' => 'ajax', '#commands' => $commands);
  }

  $node = new stdClass();
  $node->type = 'question';
  node_object_prepare($node);
  $node->title = $form_state['values']['question'];
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['value'] = $form_state['values']['description'];
  $node->body[$node->language][0]['format'] = 'filtered_html';
  $node->field_question_path[$node->language][0]['value'] = $original_path;
  node_save($node);

  $form_rebuilt = drupal_rebuild_form('quick_question', $form_state, array());
  unset($form_rebuilt['quick_question']['question']['#value']);
  unset($form_rebuilt['quick_question']['description']['#value']);
  //get related question its require to $original_path otherwise ajax call pass ajax/system path instead of current node.
  $commands[] = ajax_command_replace('#message-placeholder', _get_completion_text());
  $commands[] = ajax_command_replace('.view-questions-list', _get_relevant_questions_list($original_path));
  $commands[] = ajax_command_replace('#quick-question-wrapper', render($form_rebuilt));
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Helper Function : Returns status message to user after creating question.
 */
function _get_completion_text($message = NULL) {
  if (!$message) {
    $message = t('Your message was added to the list below.');
  }
  return '<div id="message-placeholder"><div class="text">' . $message . '<span class="close" title="close">X</span></div></div>';
}

/**
* Helper Function : Returns embeded view on lesson page.
*/
function _get_relevant_questions_list($path = NULL) {
  if(!$path) {
    $path = implode('/', arg());
  }
  return views_embed_view('relevant_questions_list', 'block', $path);
}
