<?php

/**
 * @file
 * Code for the Newsfeed feature.
 */
include_once 'newsfeed.features.inc';

/**
 * Implements hook_ctools_plugin_api().
 */
function newsfeed_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
  if ($module == 'message_notify' && $api == 'notifier') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_views_api().
 */
function newsfeed_views_api() {
  return array("api" => "3.0");
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function newsfeed_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'message_notify' && $plugin_type == 'notifier') {
    return 'plugins/notifier/internal';
  }
}

/**
 * Creates new message with given parameters.
 * 
 * @param integer $uid
 *   User ID, to which to assgin message
 * @param string $body
 *   Body of the message
 * 
 * @return Message $message
 *   Message object
 */
function newsfeed_create_message($uid, $body, $node, $uids = array()) {
  // Create message and save it with given body.
  $message = message_create('subscriptions_notification', array('uid' => $uid));
  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_message_body->set(array('value' => $body, 'format' => 'filtered_html'));
  $message->save();

  // Add parameters in order to avoid creating message for every subscriber.
  $notify_options = array(
    'internal' => array(
      'save on fail' => FALSE,
      'save on success' => FALSE,
      'mid' => $message->mid,
    )
  );
  $subscribe_options = array(
    'save message' => FALSE,
    'author' => $uid,
  );
  if (!empty($uids)) {
    $subscribe_options['uids'] = $uids;
  }

  message_subscribe_send_message('node', $node, $message, $notify_options, $subscribe_options);
}

/**
 * Implements hook_message_subscribe_get_subscribers_alter().
 * 
 * Adds 'internal' notifier if it's not set yet.
 */
function newsfeed_message_subscribe_get_subscribers_alter(&$uids, $values) {
  if (empty($uids) || is_null($notifier = message_notify_get_notifier('internal'))) {
    return;
  }
  foreach ($uids as $uid => $options) {
    // Unset node author from receivers array.
    if (isset($values['subscribe_options']['author']) && $values['subscribe_options']['author'] == $uid) {
      unset($uids[$uid]);
      continue;
    }
    // Add internal notifier if it's not added yet.
    if (!isset($options['notifiers']['internal'])) {
      $uids[$uid]['notifiers']['internal'] = 'internal';
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * Handles message-user instance deletion when message is being deleted.
 */
function newsfeed_entity_delete($entity, $entity_type) {
  if ($entity_type == 'message') {
    db_delete('message_user')
      ->condition('mid', $entity->mid)
      ->execute();
  }
}
