<?php


/**
 * Implements hook_init().
 *
 * Add quiz-specific styling.
 */
function ch_bookoblock_init() {
  // @todo Probably don't want to add this to every page.
  drupal_add_js(drupal_get_path('module', 'ch_bookoblock') . '/ch_bookoblock.js');
  drupal_add_library('system', 'ui.accordion');
}


/**
 * Define the Book Outline Block/
 * Implementation of hook_block_info()
 */
function ch_bookoblock_block_info() {
  $block['book_outline'] = array (
    'info' => 'Book Outline',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );  
  return $block;
}

/**
 * Define the contents and title of the block/
 * Implementation of hook_block_view()
 *
 * Returns a renderable block array containing the current book's outline if
 * the node is part of a book.
 *
 * Returns NULL if the current menu item is not part of a book heirarchy.
 */
function ch_bookoblock_block_view() {
  if ($book = ch_bookoblock_is_book_node()) {
    $tree = menu_tree_all_data(book_menu_name($book['bid']));
    $accordian_tree = array();
    $content = '';
    $lesson_count = 1; 
    foreach($tree as $parent => $parent_tree) { 
      foreach($parent_tree['below'] as $unit_key => $unit_tree) {
        $header_title = $unit_tree['link']['link_title'];
        $inner_tree = array();
        foreach($unit_tree['below'] as $lesson_key => $lesson) {
          $lesson_title = '<span>'."Lesson $lesson_count".'. </span>'.$lesson['link']['link_title'];
          $inner_tree[] = l($lesson_title, $lesson['link']['link_path'], array('html' => TRUE));
          $lesson_count++;
        } 
        $content .= theme('item_list', array('items' => $inner_tree, 'title' => $header_title));
      }
    }
    // If we pass 1 as the second param, we just get the top level node in the
    // book. Since the key will be the top level mlid, we'll have to use 
    // ['p1'] in the $book array (which contains the top mlid) when we use it 
    // for the block title.
    $book_name = (book_toc($book['bid'], 1));

    // Build the block title and contents
    $block['subject'] = $book_name[$book['p1']];
    $block['content'] = $content;

    // Return the block
    return $block;
  }
  // If the current node isn't part of a book, just return nothing.
  return NULL;
}

/**
 * Checks to see if current node is part of a book.
 * Returns book array if it is part of a book, FALSE is not.
 */
function ch_bookoblock_is_book_node() {
  if ((arg(0) == 'node') && (is_numeric(arg(1)))) {
    $node = menu_get_object();
    if (isset($node->book)) {
      return $node->book;
    }
  }
  return FALSE;
}
