<?php

/**
 * @file
 * Code for the Site configuration settings feature.
 */

include_once 'config.features.inc';

/**
 * Implements hook_block_info().
 */
function config_block_info() {
  $block['rights_reserved'] = array(
    'info' => t('Rights reserved block'),
  );
  return $block;
}

/**
 * Implements hook_block_view().
 */
function config_block_view($delta = '') {
  $content = array();
  $block = array();
  switch ($delta) {
    case 'rights_reserved':
      $content = array(
        '#type' => 'markup',
        '#markup' => '<div class="rights-reserved">&copy; ' . date('Y') . ' ' . t('CourseHub. All rights reserved.') . '</div>',
      );
      $block['subject'] = '';
      $block['content'] = $content;
      break;
  }
  return $block;
}

/**
 * Implements hook_menu_alter().
 */
function config_menu_alter(&$items) {
  // Disable userpoints menu item.
  $items['myuserpoints']['hidden'] = 1;
}

/**
 * Implements hook_preprocess_link().
 */
function config_preprocess_link(&$variables) {
  // Provide translatable text for custom user menu items.
  if (($variables['text'] == 'Points' || $variables['text'] == 'Profile') && $variables['path'] == 'user') {
    $variables['text'] = t($variables['text']);
  }
}

/**
 * Implements hook_menu_link_alter().
 */
function config_menu_link_alter(&$link) {
  if ($link['link_path'] == 'user/logout' && $link['module'] == 'system' && empty($link['customized'])) {
    $paren_link = db_select('menu_links', 'm')
        ->fields('m', array('mlid'))
        ->condition('m.link_title', 'User account')
        ->condition('m.link_path', 'user')
        ->execute()->fetch();
    if (isset($paren_link->mlid)) {
     $link['plid'] = $paren_link->mlid;
    }
  }
}
