<?php

/**
 * @file
 * Code for the Course module.
 */

/**
 * Implements hook_views_api().
 */
function course_views_api() {
  return array(
    'api' => '3.0', 
    'path' =>  drupal_get_path('module', 'course') . '/views', 
  );
}


/**
 * Implements hook_node_info().
 */
function course_node_info() {
  $items = array(
    'course' => array(
      'name' => t('Course'),
      'base' => 'node_content',
      'description' => t('Represent the full course.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'lesson' => array(
      'name' => t('Lesson'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'unit' => array(
      'name' => t('Unit'),
      'base' => 'node_content',
      'description' => t('Unit is a large section of course that consists of lessons, quizzes and other content. '),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'provider' => array(
      'name' => t('Provider'),
      'base' => 'node_content',
      'description' => t('Provider of course content, e.g. university or company.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}


/**
 *
 * implements hook_block_info()
 */
function course_block_info() {
  $blocks['registration_form'] = array('info' => t('Course registertion form'), );
  return $blocks;
}

/**
 *
 * implements hook_block_view()
 */
function course_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'registration_form':
      return registration_form_block();
    
  }
}




/**
 * Registration form submit hook
 */
function course_registration_form_submit($form, &$form_state) {
    global $user;
    $uid = $user->uid;
    
    if ($user->uid == 0) { //user is not logged in 
        // @todo redirect to user registration form
    }
    
    $nid = $form['nid']['#value'];
     
     // register user to the course
    $rid = course_register($uid, $nid);
    
    // @todo: redirect to the first lesson
    if($rid) {
        
    }
    
}
