<?php
/**
 * @file
 * course.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function course_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_abuse_description'
  $field_bases['field_abuse_description'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_abuse_description',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );
  // @todo barinder move functionality related to abuse flagging to separate
  // module outside of course. this should be as generic as abuse contrib module.
  // 
  // Exported field_base: 'field_abuse_reason'
  $field_bases['field_abuse_reason'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_abuse_reason',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        // @todo barinder make proper translatable values for spam and offencive language 
        'reason_1' => 'Reason 1',
        'reason_2' => 'Reason 2',
        'reason_3' => 'Reason 3',
        'reason_4' => 'Reason 4',
        'reason_5' => 'Reason 5',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
