<?php

/**
 * @file 
 * answers_extra.module
 */

/**
 * Implements hook_init() to redirect from answer nodes to questions.
 */
function answers_extra_init() {
  $node = menu_get_object('node', 1);
  if($node && $node->type == 'answer') {
    $question = entity_metadata_wrapper('node', $node);
    drupal_goto('node/' . $question->field_answer_question->raw(), array('fragment' => "answer-".$node->nid), '302');   
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function answers_extra_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function answers_extra_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'answers_extra') . '/views',);
}

/**
 * Implements hook_block_info().
 */
function answers_extra_block_info() {
  $block['question_answers'] = array(
    'info' => t('List of Question Answers'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $block;
}

/**
 * Implements of hook_block_view().
 */
function answers_extra_block_view($delta = '') {
  $content = array();
  $block = array();
  switch($delta) {
    case 'question_answers':
      //Placeholder for message. 
      $content['message_placeholder'] = array(
        '#type' => 'markup',
        '#markup' => '<div id="message-placeholder"></div>',
      );
      // Embed view 
      $content['answers_list'] = array(
        '#type' => 'markup',
        '#markup' => _get_relevant_answers_list(),
      );
      // Question form
      $content['answer_form'] = drupal_get_form('quick_answer');
      // Build the block title and contents
      $block['subject'] = '';
      $block['content'] = $content;
      break;    
  }
  return $block;
}

/**
* Helper Function : Returns embeded view on lesson page.
*/
function _get_relevant_answers_list($nid = NULL) {
  if(!$nid) {
    $nid = arg(1);
  }
  return views_embed_view('answers_to_a_question_extra', 'block_answers', $nid);
}



/**
 * Build a form for answers on question page
 */
function quick_answer($form, &$form_state) {
  if (!user_access('create answer content')) {
    return;
  }
  
  $form['fields'] = array(
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#prefix' => '<div id="quick-answer-wrapper">',
    '#suffix' => '</div>',
    '#title' => t('Give Answer')
  );

  if(isset($form_state['values']['question'])) {
    $question_nid = $form_state['values']['question'];
  }
  else {
    $question_node = menu_get_object('node');
    if(!$question_node || $question_node->type <> 'question') {
      return;
    }
    $question_nid = $question_node->nid;
  }

  $form['fields']['question'] = array(
    '#type' => 'hidden',
    '#value' => $question_nid
  );

  $form['fields']['answer'] = array(
    '#type' => 'text_format',
    '#format' => 'filtered_html',
    '#attributes' => array('placeholder' => t('Answer')),
    '#rows' => 3,
    '#cols' => 73,
  );

  $form['fields']['submit'] = array(
    '#type' => 'submit',
    '#ajax' => array(
      'callback' => 'quick_answer_submit_callback',
      'wrapper' => 'quick-answer-wrapper',
    ),
    '#value' => t('Save'),
  );
  return $form;
}

/**
 * Submit function for quick answer form
 */
function quick_answer_submit($form, &$form_state) {
   global $user;
  //validations
  if (!$form_state['values']['answer']['value']) {
    $message = t('Answer cannot be empty.'); // @todo add js to disable button if field is empty.
    $commands[] = ajax_command_replace('#message-placeholder', _get_completion_text($message));
    return array('#type' => 'ajax', '#commands' => $commands);
  }

  $node = new stdClass();
  $node->type = 'answer';
  node_object_prepare($node);
  $node->title = 'Answer of uid# ' . $user->uid . ' for question #nid ' . $form_state['values']['question'];
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['value'] = $form_state['values']['answer']['value'];
  $node->body[$node->language][0]['format'] = 'filtered_html';
  $node->field_answer_question[$node->language][0]['nid'] = $form_state['values']['question'];
  node_save($node);
  
  unset($form_state['values']['answer']);
  $form_state['rebuild'] = TRUE;
}

/**
 * Callback function : Ajax callback function for quick_answer form.
 */
function quick_answer_submit_callback($form, &$form_state) {
  //get related question its require to $original_path otherwise ajax call pass ajax/system path instead of current node.
  $commands[] = ajax_command_replace('#message-placeholder', _get_completion_text(t('Your answer added to the list below.')));
  $commands[] = ajax_command_replace('.view-question-answers', _get_relevant_answers_list($form_state['values']['question']));
  //unset Answers
  unset($form['fields']['answer']['value']['#value']);
  $commands[] = ajax_command_replace('#quick-answer-wrapper', render($form));
  return array('#type' => 'ajax', '#commands' => $commands);
}


/**
 * Implements hook_subscriptions_reference_info()
 */
function answers_extra_subscriptions_reference_info() {
  return array(
    'question_answers' => array(
      'parent' => 'question',
      'child' => 'answer',
      'field' => 'field_answer_question',
      'ref_item' => 'nid',
  ));
}

/**
 *  Implements hook_preprocess_views_view_fields 
 *  for relevant_questions_list view.
 */
function answers_extra_preprocess_views_view_fields(&$vars) {
  $view = $vars['view'];
 // print_nice($view, 3);
  $question_list_views = array('relevant_questions_list', 'user_questions_list');
  if (!in_array($view->name, $question_list_views)) {
    return;
  }
  
  $row = $vars['row'];
  if (isset($row->field_field_answer_count[0])) {
    $answers = $row->field_field_answer_count[0]['raw']['count'];
    $ccs_classes = 'field-answer-count';
    if (!$answers) {
      $ccs_classes = $ccs_classes . ' zero';
    }
    $output = 
     '<div class="' . $ccs_classes .  '">' .
       format_plural($answers, '1 <br />Answer', '@count <br />Answers') . 
     '</div>';
    
    // Replace content of the field.
    $answers_count_field = $vars['fields']['field_answer_count'];
    $answers_count_field->content = $output;
  }  
}

/**
 * Implements hook_userpoints().
 * 
 * Prevents account's userpoints from going (further) negative.
 */
function answers_extra_userpoints($op, &$params) {
  if ($op == 'points before' && isset($params['points']) && $params['points'] < 0) {
    $current_points = userpoints_get_current_points($params['uid'], $params['tid']);
    $new_points = $current_points + $params['points'];
    // If points are going to be negative or negative already cancel current transaction
    // and perform transaction, that set points to zero.
    if ($new_points < 0) {
      $params['points'] = 0 - $current_points;
      return TRUE;
    }
  }
}


/**
 * Form for inline question editing.
 */
function answers_extra_question_form($form, &$form_state) {
  $form = array();
  $form['#prefix'] = "<div id='node-question-form'>";
  $form['#suffix'] = '</div>';

  if (!isset($form_state['storage']['question'])) {
    $form_state['storage']['question'] = menu_get_object('node');
  }
  $question = $form_state['storage']['question'];

  if (!$question || $question->type !== 'question') {
      return $form;
  }
  
  if (!isset($form_state['step'])) {  // page is loaded
    $form_state['step'] =  'view';
  }
   
  // build form depending on it's current mode
  switch ($form_state['step']) {
    case 'view':
      $form['view']['edit'] = array(
        '#name' => 'edit',
        '#type' => 'submit',
        '#value' => t('Edit'),
        '#submit' => array('answer_extra_question_form_edit'),
        '#ajax' => array(
          'callback' => 'answers_extra_question_form_js',
          'wrapper' => 'node-question-form',
          'progress' => array('message' => ''),
        ),
      );
      break;
    
    case 'edit' :
      // build form for editing
      $question_wrapper = entity_metadata_wrapper('node', $question);
      $question_body = $question_wrapper->body->value();
     
      $form['edit']['title'] = array(
        '#type' => 'textfield',
        '#default_value' => $question->title
      );
     
      $form['edit']['body'] = array(
        '#type' => 'text_format',
        '#format' => 'filtered_html',
        '#default_value' => $question_body['value']
      );
      
      $form['edit']['save'] = array(
        '#name' => 'save',
        '#type' => 'submit',
        '#submit' => array('answers_extra_question_form_save'),
        '#value' => t('Save'),
        '#ajax' => array(
          'callback' => 'answers_extra_question_form_js',
          'wrapper' => 'node-question-form',
          'progress' => array('message' => ''),
        ),
      );
      break;
    
    default :
      $form['bad_state'] = array(
        '#type' => 'markup',
        '#markup' => t('State @mode is not supported by this form.', array('@mode' => $mode)),
      );
  }

  return $form;
}

/**
 * Form submit for edit mode inline question editing.
 */
function answer_extra_question_form_edit($form, &$form_state) {
  $form_state['step'] = 'edit';
  $form_state['rebuild'] = TRUE;
}

/**
 * Implements submit function for the question editing form
 */
function answers_extra_question_form_save($form, &$form_state) {
  $question = $form_state['storage']['question'];
  $question->title = $form_state['values']['title'];
  $question->body[$question->language][0]['value'] = $form_state['values']['body']['value'];
  $question->body[$question->language][0]['format'] = 'filtered_html';
  node_save($question);

  $form_state['step'] = 'view';
  $form_state['rebuild'] = TRUE;

  // Temporary workaround for showing updated content to user.
  // @todo : Find some another way to refresh node.
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  $commands[] = ctools_ajax_command_reload();
  print ajax_render($commands);
  exit;

}

/**
 * Callback for question edit js submit
 */
function answers_extra_question_form_js($form, &$form_state) {
  return $form;
}

/**
 * Form for inline answer editing.
 */
function answers_extra_answer_form($form, &$form_state, $nid) {
  $form = array();
  $form['#prefix'] = "<div id='node-answer-form-$nid'>";
  $form['#suffix'] = '</div>';

  if (!isset($form_state['storage']['answer'])) {
    $form_state['storage']['answer'] = node_load($nid);
  }
  $answer = $form_state['storage']['answer'];

  if (!$answer || $answer->type !== 'answer') {
    return $form;
  }
  
  if (!isset($form_state['step'])) {  // page is loaded
    $form_state['step'] =  'view';
  }
   
  // build form depending on it's current mode
  switch ($form_state['step']) {
    case 'view':
      $form['view']['edit'] = array(
        '#name' => 'edit',
        '#type' => 'submit',
        '#value' => t('Edit'),
        '#submit' => array('answers_extra_answer_form_edit'),
        '#ajax' => array(
          'callback' => 'answers_extra_answer_form_js',
          'wrapper' => "node-answer-form-$nid",
          'progress' => array('message' => ''),
        ),
      );
      break;
    
    case 'edit' :
      // build form for editing
      $answer_wrapper = entity_metadata_wrapper('node', $answer);
      $answer_body = $answer_wrapper->body->value();
     
      $form['edit']['body'] = array(
        '#type' => 'text_format',
        '#format' => 'filtered_html',
        '#default_value' => $answer_body['value']
      );
      
      $form['edit']['save'] = array(
        '#name' => 'save',
        '#type' => 'submit',
        '#submit' => array('answers_extra_answer_form_save'),
        '#value' => t('Save'),
        '#ajax' => array(
          'callback' => 'answers_extra_answer_form_js',
          'wrapper' => "node-answer-form-$nid",
          'progress' => array('message' => ''),
        ),
      );
      break;
    
    default :
      $form['bad_state'] = array(
        '#type' => 'markup',
        '#markup' => t('State @mode is not supported by this form.', array('@mode' => $mode)),
      );
  }

  return $form;

}

/**
 * Form submit for edit mode inline answer editing.
 */
function answers_extra_answer_form_edit($form, &$form_state) {
  $form_state['step'] = 'edit';
  $form_state['rebuild'] = TRUE;
}

/**
 * Implements submit function for the answer editing form
 */
function answers_extra_answer_form_save($form, &$form_state) {
  $answer = $form_state['storage']['answer'];
  $answer->body[$answer->language][0]['value'] = $form_state['values']['body']['value'];
  $answer->body[$answer->language][0]['format'] = 'filtered_html';
  node_save($answer);

  $form_state['step'] = 'view';
  $form_state['rebuild'] = TRUE;

  // Temporary workaround for showing updated content to user.
  // @todo : Find some another way to refresh node.
  ctools_include('ajax');
  ctools_add_js('ajax-responder');
  $commands[] = ctools_ajax_command_reload();
  print ajax_render($commands);
  exit;
}

/**
 * Callback for answer edit js submit
 */
function answers_extra_answer_form_js($form, &$form_state) {
  return $form;
}
