<?php

/**
 * @file
 * Additional functionality to Best Answer module.
 */

/**
 * Implements hook_flag_access_multiple().
 */
function best_answer_extra_flag_access_multiple($flag, $entity_ids, $account) {
  // @todo Ilya: find a better way to show best answer to others
  if ($flag->name == 'best_answer') {
    $access = array();
    foreach ($entity_ids as $entity_id => $type) {
      $question = entity_metadata_wrapper('node', $entity_id)->field_answer_question->value();
      if ($question && $question->uid != $account->uid) {
         $access[$entity_id] = FALSE;
      }
    }
    return $access;
  }
}

/**
 * Implements hook_node_view().
 */
function best_answer_extra_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'question' && $view_mode == 'full') {
    drupal_add_js(drupal_get_path('module', 'best_answer_extra') . '/best_answer_extra.js');
  }
}

/**
 * Implements hook_flag().
 *
 * Fires on flag event to control that there is only one best answer per question.
 * TODO: Create test for this hook to ensure that when flagged an answer as best the rest of 
 * answers are unflagged and the answers of other questions remain flagged (at least one answer flagged)
 */
function best_answer_extra_flag_flag($flag, $entity_id, $account, $flagging) {
 
  if ($flag->name == "best_answer") {
    $question = entity_metadata_wrapper('node', $entity_id)->field_answer_question->value();
    
    $query = new EntityFieldQuery();
    $entities = $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'answer')
      ->propertyCondition('nid', $entity_id, '<>')
      ->fieldCondition('field_answer_question', 'nid', $question->nid, '=')
      ->execute();
    
    foreach ($entities as $type => $answers) {
      foreach ($answers as $nid => $answer) {
        if ($flag->is_flagged($nid)) {
          $flag->flag('unflag', $nid);
        }
      }
    }
  }
}
