<?php

/**
 * @file
 * Code for the test feature.
 */

include_once 'subscriptions_question.features.inc';

/**
 * @file
 * Subscriptions to questions.
 *
 * subscriptions_question extends the subscription_reference module to allow users to
 * subscribe questions. If a user subscribes to a question he will receive
 * notifications each time an answer is posted to that question. 
 */

DEFINE('QUESTION_REFERENCE_FIELD', 'field_answer_question');
/**
 * Implements hook_subscriptions_reference_info()
 */
function subscriptions_question_subscriptions_reference_info() {
  return array(
    'question_answers' => array(
      'parent' => 'question',
      'child' => 'answer',
      'field' => QUESTION_REFERENCE_FIELD,
      'ref_item' => 'nid',
  ));
}
