<?php
/**
 * @file
 * Code for the Course Blog feature.
 */

include_once 'course_blog.features.inc';

/**
 *  Implements of hook_node_access()
 */
function course_blog_node_access($node, $op, $account) {

  // allow teacher to create blog.
  if($op == 'update' && $node->type == 'blog' && !course_is_teacher($node, $account)) {
    return NODE_ACCESS_DENY;
  }
  
  // Allow registered students to access the blog.
  if(isset($node->type) && $node->type === 'blog' && $op == 'view') {
    $item = entity_metadata_wrapper('node', $node);
    $course = $item->field_course->value();
    if(!course_registration_id($account->uid, $course->nid)) {
      return NODE_ACCESS_DENY;
    }
  }
}
