<?php



/**
 * Implements hook_block_info()
 */
function course_outline_block_info() {
  $block['book_outline'] = array(
    'info' => 'Course Outline',
  //  'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $block;
}


/**
 * Implements hook_theme()
 */
function course_outline_theme() {
  return array(
        'menu_link__course_outline_unit' => array(
           'render element' => 'element'        
        )
    );
}

/**
 * Returns HTML for the unit level elements of the course outline
 */
function theme_menu_link__course_outline_unit(array $variables) {
  $element = $variables['element'];
  $sub_menu = '';
  $output = "<h3>" . $element['#title'] .'<span class="icon"></span>'. '</h3>';
  if ($element['#below']) {
    $sub_menu = drupal_render($element['#below']);
  }   
  return $output . $sub_menu . "\n";
}


/**
 * Define the contents and title of the block/
 * Implementation of hook_block_view()
 *
 * Returns a renderable block array containing the current book's outline if
 * the node is part of a book.
 *
 * Returns NULL if the current menu item is not part of a book heirarchy.
 */
function course_outline_block_view($delta = '') {
  $book = course_node_book();
  if (!$book) {
    return NULL;
  }
  
  drupal_add_js(drupal_get_path('module', 'course_outline') . '/course_outline.js');
  drupal_add_css(drupal_get_path('module', 'course_outline') . '/course_outline.css');
  drupal_add_library('system', 'ui.accordion');

  $tree = menu_tree_all_data($book['menu_name'], NULL, 3);
  course_outline_preprocess_tree($tree);

  // If we pass 1 as the second param, we just get the top level node in the
  // book. Since the key will be the top level mlid, we'll have to use 
  // ['p1'] in the $book array (which contains the top mlid) when we use it 
  // for the block title.
  $book_name = book_toc($book['bid'], 1);

  $tree_output = menu_tree_output($tree);
  // alter titles and classes of the links in the tree
  course_outline_preprocess_tree($tree_output);

  // Build the block title and contents
  $block['subject'] = ''; //$book_name[$book['p1']];
  $block['content'] = $tree_output;
  
  return $block;
}

/**
 * Adds content type specific html to leafs of course menu
 * @param array $tree represents menu tree
 * @return boolean
 */
function course_outline_preprocess_tree(&$tree) {
  global $user;
  $counter = new multi_counter;
  $tree_key = key($tree);    
  if(isset($tree[$tree_key]['#below'])){
    $tree = $tree[$tree_key]['#below']; // remove the top level
    $flag = flag_get_flag('course_item_complete');
    foreach ($tree as &$unit) {
      if(!isset($unit['#below'])) { 
        continue;
      }
      // change theme for unit level links
      $unit['#theme'] = 'menu_link__course_outline_unit';
      // for each lesson we add html to the title
      foreach ($unit['#below'] as &$item) {
        if(!isset($item['#below'])) {
          continue;
        }
        $node = menu_get_object('node', 1, $item['#original_link']['link_path']);
     
        $completed = $flag->is_flagged($node->nid, $user->uid);
        $item['#attributes']['class'][] = $completed ? 'completed' : 'incompleted';
        if ($node->nid == arg(1)) {
          $item['#attributes']['class'][] = 'current';
        }
        $node->order = $counter->increment($node->type);
     
        $item['#title'] = course_outline_item_title($node);
        $item['#localized_options']['html'] = TRUE;
        $item['#attributes']['class'][] = $node->type;
      }
    }  
  }  
}
/**
 * Builds title for course outline menu item
 * @param object $node
 * @return string title for the course outline menu item
 */
function course_outline_item_title($node){
  switch ($node->type) {
        case 'lesson':
          $title = "<span class='" . $node->type . "'>" . t('Lesson @i.', array('@i' => $node->order)) . '</span>';
          break;
        case 'quiz': // @todo : add question mark icon.
          $title = "<span class='" . $node->type . "'></span>";
          break;
        default:
          $title = "<span class='" . $node->type . "'></span>";
          break;
      }
      $title = '<div class="title-wrapper">'.$title . $node->title.'</div>';
   return $title;
}


/**
 * Helper counter class allows to keep several counts
 */
class multi_counter {

  private $counts;

  public function __construct() {
    $this->counts = array();
  }

  /**
   * Increments counter of specific type by one
   * @param string $type
   * @return integer
   */
  public function increment($type) {
    if (!isset($this->counts[$type])) {
      return $this->counts[$type] = 1;
    }
    else {
      return++$this->counts[$type];
    }
  }

  /**
   * Gets current value of counter
   * @param string $type
   * @return integer
   */
  public function current($type) {
    if (!isset($this->counts[$type])) {
      return 0;
    }
    else {
      return $this->counts[$type];
    }
  }

}
